/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import Base.Bitacora;
import Base.Departamento;
import Base.Empleado;
import Beans.BitacoraBean;
import Beans.DepartamentoBean;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author less_
 */
public class BitacoraC extends javax.swing.JFrame {
    static int ban = 0;
    private int valor = 0 ;
    private ArrayList<BitacoraBean> listBitaB = new ArrayList();
    private DepartamentoBean deptoB = new DepartamentoBean();
    private BitacoraBean bitaB = new BitacoraBean();
    private Departamento depto;
    private Empleado empleado;
    private Bitacora bita;
    private String Cargo;
    /**
     * Creates new form Bitacora
     */
    public BitacoraC() {
        initComponents();        
    }

    public BitacoraC(String Departamento, String idCargo) throws SQLException {
        ban = 1;
        initComponents();
        Inicio(idCargo);
        if (idCargo.equals("1")) {//// JEFE DESARROLLO
            depto = new Departamento();
            empleado = new Empleado();
            bita = new Bitacora();
            ListarProgramadores(Departamento);
            VerlistaProCaso(1);
        }
        else if (idCargo.equals("2")){// JEFE FUNCIONAL            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlHead = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnMenuCasos = new javax.swing.JLabel();
        txtProgramador = new javax.swing.JTextField();
        pnlBody = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblNombreCaso = new javax.swing.JLabel();
        lblIdCaso = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listUser = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblPorcentaje = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listCasos = new javax.swing.JList<>();
        lblCasoPro = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(59, 134, 139));
        jLabel8.setText("Codigo de caso");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHead.setBackground(new java.awt.Color(59, 134, 139));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bitacora");

        btnMenuCasos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/images/icons8-menú-2-filled-50.png"))); // NOI18N
        btnMenuCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuCasosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(137, 137, 137)
                .addComponent(btnMenuCasos)
                .addContainerGap())
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addComponent(btnMenuCasos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 70));

        txtProgramador.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtProgramador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 134, 139), 1, true));
        getContentPane().add(txtProgramador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(59, 134, 139));
        jLabel6.setText("Nombre del caso");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(59, 134, 139));
        jLabel7.setText("Codigo de caso");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(59, 134, 139));
        jLabel9.setText("Descripción de actividad");

        txtObservaciones.setColumns(20);
        txtObservaciones.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtObservaciones.setRows(5);
        txtObservaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 134, 139), 1, true));
        jScrollPane1.setViewportView(txtObservaciones);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(59, 134, 139));
        jLabel10.setText("Observaciones");

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 134, 139), 1, true));
        txtDescripcion.setEnabled(false);
        jScrollPane2.setViewportView(txtDescripcion);

        lblNombreCaso.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreCaso.setForeground(new java.awt.Color(0, 51, 102));
        lblNombreCaso.setText("Nombre");

        lblIdCaso.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblIdCaso.setForeground(new java.awt.Color(0, 51, 102));
        lblIdCaso.setText("Nombre");

        listUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUserMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listUser);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(59, 134, 139));
        jLabel13.setText("Programadores");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(59, 134, 139));
        jLabel14.setText("Porcentaje");

        lblPorcentaje.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPorcentaje.setForeground(new java.awt.Color(0, 51, 102));
        lblPorcentaje.setText("Nombre");

        listCasos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listCasos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCasosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listCasos);

        lblCasoPro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCasoPro.setForeground(new java.awt.Color(59, 134, 139));
        lblCasoPro.setText("Casos");

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombreCaso, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(lblIdCaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(lblPorcentaje)))
                .addGap(18, 18, 18)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(lblCasoPro))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(lblIdCaso))
                                .addGap(18, 18, 18)
                                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lblNombreCaso)))
                            .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(lblPorcentaje)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCasoPro)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ban = 0;
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnMenuCasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuCasosMouseClicked
        if (valor == 0) {
            Mostrar();
            valor = 1;
        }
        else{ 
            Ocultar();
            valor = 0;
        }
    }//GEN-LAST:event_btnMenuCasosMouseClicked

    private void listUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUserMouseClicked
        if (Cargo.equals("1")) {
            if (listUser.getModel().getSize() > 0) {
                int idProg = Integer.parseInt(String.valueOf(listUser.getSelectedValue()));
                bita.getBitacoraProgramador(idProg, listBitaB);
                if (!listBitaB.isEmpty()) {
                    VerlistaProCaso(0);
                    LlenarlistaProCaso();
                }
                else
                    JOptionPane.showMessageDialog(null, "El Programador con ID "+String.valueOf(listUser.getSelectedValue())+"\nAun no ha realizado una bitacora");
            }
        }
    }//GEN-LAST:event_listUserMouseClicked

    private void listCasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCasosMouseClicked
        MostrarBitacora(listCasos.getSelectedValue());
    }//GEN-LAST:event_listCasosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BitacoraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BitacoraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BitacoraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BitacoraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BitacoraC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMenuCasos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCasoPro;
    private javax.swing.JLabel lblIdCaso;
    private javax.swing.JLabel lblNombreCaso;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JList<String> listCasos;
    private javax.swing.JList<String> listUser;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtObservaciones;
    public static javax.swing.JTextField txtProgramador;
    // End of variables declaration//GEN-END:variables

    private void VerlistaProCaso(int i){
        if (i == 0) {
            lblCasoPro.setVisible(true);
            listCasos.setVisible(true);
        }
        else{
            lblCasoPro.setVisible(false);
            listCasos.setVisible(false);
        }
    }
    
    private void Ocultar() {
        listUser.setVisible(false);
        this.setSize(490,this.getSize().height);
        pnlHead.setSize(490,pnlHead.getSize().height);
        pnlBody.setSize(490,pnlBody.getSize().height);
        btnMenuCasos.setLocation(pnlHead.getSize().width - btnMenuCasos.getSize().width-20, btnMenuCasos.getLocation().y);
    }

    private void Mostrar() {
        listUser.setVisible(true);
        this.setSize(656, this.getSize().height);
        pnlHead.setSize(656, pnlHead.getSize().height);
        pnlBody.setSize(656, pnlBody.getSize().height);
        btnMenuCasos.setLocation(pnlHead.getSize().width - btnMenuCasos.getSize().width-20, btnMenuCasos.getLocation().y);
    }

    private void ListarProgramadores(String Departamento) {
        try {            
            deptoB = depto.getDatos(Departamento);
            empleado.getProTrabajando(String.valueOf(deptoB.getId_depto()), listUser);
        } catch (Exception e) {
            System.out.println(""+e);
        }
    }

    private void Inicio(String idCargo) {
        this.setLocationRelativeTo(null);
        this.setLayout(null);
        pnlHead.setLayout(null);
        pnlBody.setLayout(null);
        lblIdCaso.setVisible(false);
        lblNombreCaso.setVisible(false);
        lblPorcentaje.setVisible(false);
        Ocultar();
        this.Cargo = idCargo;
    }

    private void LlenarlistaProCaso() {
        listCasos.clearSelection();        
        DefaultListModel modelo = new DefaultListModel();
        for (BitacoraBean bitacoraBean : listBitaB) {
            modelo.addElement(bitacoraBean.getId_caso());
        }
        listCasos.setModel(modelo);
    }

    private void MostrarBitacora(String selectedValue) {
        for (BitacoraBean bitacoraBean : listBitaB) {
            if (bitacoraBean.getId_caso().equals(selectedValue)) {
                lblIdCaso.setVisible(true);
                lblNombreCaso.setVisible(true);
                lblPorcentaje.setVisible(true);
                lblIdCaso.setText(bitacoraBean.getId_caso());
                lblNombreCaso.setText(bitacoraBean.getNombre_caso());
                lblPorcentaje.setText(bitacoraBean.getPorcentaje()+" %");
                txtDescripcion.setText(bitacoraBean.getDescripActiv());
                txtObservaciones.setText(bitacoraBean.getObservaciones());
                break;
            }
        }
    }

    private void dato() {
//                    JOptionPane.showMessageDialog(null, ""+listUser.getSelectedValue());
//            String valor = listUser.getSelectedValue();
//                JOptionPane.showMessageDialog(null, ""+valor);
            //int id = Integer.parseInt(valor);//Integer.parseInt(listUser.getSelectedValue().toString());            
//            bita.getBitacoraProgramador(id, listBitaB);
            VerlistaProCaso(0);
//            LlenarlistaProCaso();
    }
}
