/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import Base.Bitacora;
import Base.Casos;
import Base.Departamento;
import Base.Empleado;
import Beans.BitacoraBean;
import Beans.CasoBean;
import Beans.DepartamentoBean;
import Beans.EmpleadoBean;
import Help.Help;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author less_
 */
public class BitacoraC extends javax.swing.JFrame {
    static int ban = 0;
    private int valor = 0 ;
    private ArrayList<BitacoraBean> listBitaB = new ArrayList();
    private BitacoraBean bitaB = new BitacoraBean();
    private CasoBean casoB = new CasoBean();
    private Help h  = new Help();
    private Empleado empleado;
    private Casos caso;
    private Bitacora bita;
    private int IdCargo;
    private int IdDepto;
    private int statusCaso;
    //Proeuba
    private EmpleadoBean men;
    //
    /**
     * Creates new form Bitacora
     */
    public BitacoraC() {
        initComponents();        
    }

    public BitacoraC(int Iddepto, String Departamento, int idCargo, Menu aThis, EmpleadoBean User) throws SQLException {
        ban = 1;
        aThis.dispose();        
        men = User;
        initComponents();
        this.setLocationRelativeTo(null);
        Inicio(idCargo);
        bita = new Bitacora();
        switch (idCargo) {
            case 1://// JEFE DESARROLLO
                this.IdDepto = Iddepto;
                empleado = new Empleado();
                ListarProgramadores(Departamento);
                VerlistaProCaso(1);
                noProniEmp();
                break;
            case 2:// JEFE FUNCIONAL
                lblProOoCasos.setText("Casos Aperturados");
                ListarCasos(Departamento);
                noProniEmp();
                break;
            case 3://PROGRAMADOR---> Departamento = IdCaso
                btnMenuCasos.setVisible(false);
                bita.getBitacoraCaso(Departamento, bitaB);
                if (bitaB.getId_caso().length() > 0) {
                    MostrarBitacoraJF();//Cargando Bitacora del Caso
                    llenandoCb();
                    ProgEmp(0);
                }
                break;
            case 4://Empleado---> Departamento = IdCaso
                btnMenuCasos.setVisible(false);
                cbPorcentaje.setEnabled(false);
                bita.getBitacoraCaso(Departamento, bitaB);//Cargando Bitacora del Caso
                if (bitaB.getId_caso().length() > 0) {
                    MostrarBitacoraJF();
                    llenandoCb();
                    ProgEmp(1);
                    //Ver si el caso esta esperando la respuesta de 
                    //sino no muestras los botones de acciones
                    if (!isWaitAnswer()){ 
                        BtnsEmp(0);
                        txtObservaciones.setEditable(false);
                    }
                    
                }               
                break;
        }
    }    

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlHead = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnMenuCasos = new javax.swing.JLabel();
        txtProgramador = new javax.swing.JTextField();
        pnlBody = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblNombreCaso = new javax.swing.JLabel();
        lblIdCaso = new javax.swing.JLabel();
        ScrollListUser = new javax.swing.JScrollPane();
        listUser = new javax.swing.JList<>();
        lblProOoCasos = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblPorcentaje = new javax.swing.JLabel();
        ScrollListCasos = new javax.swing.JScrollPane();
        listCasos = new javax.swing.JList<>();
        lblCasoPro = new javax.swing.JLabel();
        cbPorcentaje = new javax.swing.JComboBox<>();
        btnFinalizar = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnUpdateBitacora = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnRechazar = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        lblFechaProduccion = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(59, 134, 139));
        jLabel8.setText("Codigo de caso");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHead.setBackground(new java.awt.Color(59, 134, 139));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bitacora");

        btnMenuCasos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/images/icons8-menú-2-filled-50.png"))); // NOI18N
        btnMenuCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuCasosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(137, 137, 137)
                .addComponent(btnMenuCasos)
                .addContainerGap())
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addComponent(btnMenuCasos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 70));

        txtProgramador.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtProgramador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 134, 139), 1, true));
        getContentPane().add(txtProgramador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(59, 134, 139));
        jLabel6.setText("Nombre del caso");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(59, 134, 139));
        jLabel7.setText("Codigo de caso");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(59, 134, 139));
        jLabel9.setText("Descripción de actividad");

        txtObservaciones.setColumns(20);
        txtObservaciones.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtObservaciones.setRows(5);
        txtObservaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 134, 139), 1, true));
        txtObservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObservacionesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtObservaciones);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(59, 134, 139));
        jLabel10.setText("Observaciones");

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 134, 139), 1, true));
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtDescripcion);

        lblNombreCaso.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreCaso.setForeground(new java.awt.Color(0, 51, 102));
        lblNombreCaso.setText("Nombre");

        lblIdCaso.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblIdCaso.setForeground(new java.awt.Color(0, 51, 102));
        lblIdCaso.setText("Nombre");

        listUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUserMouseClicked(evt);
            }
        });
        ScrollListUser.setViewportView(listUser);

        lblProOoCasos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblProOoCasos.setForeground(new java.awt.Color(59, 134, 139));
        lblProOoCasos.setText("Programadores");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(59, 134, 139));
        jLabel14.setText("Porcentaje");

        lblPorcentaje.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPorcentaje.setForeground(new java.awt.Color(0, 51, 102));
        lblPorcentaje.setText("Nombre");

        listCasos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listCasos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCasosMouseClicked(evt);
            }
        });
        ScrollListCasos.setViewportView(listCasos);

        lblCasoPro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCasoPro.setForeground(new java.awt.Color(59, 134, 139));
        lblCasoPro.setText("Casos");

        cbPorcentaje.setBorder(null);

        btnFinalizar.setBackground(new java.awt.Color(89, 199, 198));
        btnFinalizar.setToolTipText("Finalizar Bitacora");
        btnFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Finalizar");

        javax.swing.GroupLayout btnFinalizarLayout = new javax.swing.GroupLayout(btnFinalizar);
        btnFinalizar.setLayout(btnFinalizarLayout);
        btnFinalizarLayout.setHorizontalGroup(
            btnFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFinalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnFinalizarLayout.setVerticalGroup(
            btnFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFinalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUpdateBitacora.setBackground(new java.awt.Color(89, 199, 198));
        btnUpdateBitacora.setToolTipText("Actualizar");
        btnUpdateBitacora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateBitacoraMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Actualizar Bitacora");

        javax.swing.GroupLayout btnUpdateBitacoraLayout = new javax.swing.GroupLayout(btnUpdateBitacora);
        btnUpdateBitacora.setLayout(btnUpdateBitacoraLayout);
        btnUpdateBitacoraLayout.setHorizontalGroup(
            btnUpdateBitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUpdateBitacoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnUpdateBitacoraLayout.setVerticalGroup(
            btnUpdateBitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUpdateBitacoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRechazar.setBackground(new java.awt.Color(89, 199, 198));
        btnRechazar.setToolTipText("Rechazar Cambios");
        btnRechazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRechazarMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Rechazar");

        javax.swing.GroupLayout btnRechazarLayout = new javax.swing.GroupLayout(btnRechazar);
        btnRechazar.setLayout(btnRechazarLayout);
        btnRechazarLayout.setHorizontalGroup(
            btnRechazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRechazarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnRechazarLayout.setVerticalGroup(
            btnRechazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRechazarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAceptar.setBackground(new java.awt.Color(89, 199, 198));
        btnAceptar.setToolTipText("Aceptar Cambio");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Aceptar");

        javax.swing.GroupLayout btnAceptarLayout = new javax.swing.GroupLayout(btnAceptar);
        btnAceptar.setLayout(btnAceptarLayout);
        btnAceptarLayout.setHorizontalGroup(
            btnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAceptarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAceptarLayout.setVerticalGroup(
            btnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAceptarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFechaProduccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFechaProduccion.setForeground(new java.awt.Color(59, 134, 139));
        lblFechaProduccion.setText("Fecha Produccion");

        txtFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtFecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 134, 139), 1, true));
        txtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaMouseClicked(evt);
            }
        });
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombreCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(cbPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(25, 25, 25)
                                .addComponent(lblIdCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(lblPorcentaje))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdateBitacora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblFechaProduccion)
                                .addGap(43, 43, 43)))
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollListUser, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(ScrollListCasos, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(lblProOoCasos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblCasoPro)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(lblIdCaso))
                                .addGap(18, 18, 18)
                                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lblNombreCaso)))
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(lblPorcentaje))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(lblProOoCasos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollListUser, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCasoPro)
                        .addGap(10, 10, 10)
                        .addComponent(ScrollListCasos, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaProduccion)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUpdateBitacora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(pnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ban = 0;
        new Menu(men).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnMenuCasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuCasosMouseClicked
        if (valor == 0) {
            Mostrar();
            valor = 1;
        }
        else{ 
            Ocultar();
            valor = 0;
        }
    }//GEN-LAST:event_btnMenuCasosMouseClicked

    private void listUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUserMouseClicked
        if (IdCargo == 1) {
            if (listUser.getModel().getSize() > 0) {
                int idProg = Integer.parseInt(String.valueOf(listUser.getSelectedValue()));
                bita.getBitacorasProgramadorToJD(idProg, listBitaB);
                if (!listBitaB.isEmpty()) {
                    VerlistaProCaso(0);
                    LlenarlistaProCaso();
                }
                else
                    JOptionPane.showMessageDialog(null, "El Programador con ID "+String.valueOf(listUser.getSelectedValue())+"\nAun no ha realizado una bitacora");
            }
        }
        else if (IdCargo == 2) {
            if (listUser.getModel().getSize() > 0) {
                String idCaso1 = String.valueOf(listUser.getSelectedValue());
                bita.getBitacoraCaso(idCaso1, bitaB);
                if (bitaB.getId_caso().length() > 0) {
                    MostrarBitacoraJF();
                }
            }
        }        
    }//GEN-LAST:event_listUserMouseClicked

    private void listCasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCasosMouseClicked
        ShowBitacoraJD(listCasos.getSelectedValue());
    }//GEN-LAST:event_listCasosMouseClicked

    private void btnFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarMouseClicked
        // PROGARMADOR: FINALIZA CASO-------Esperando respuesta
        try {
            bitaB.setDescripActiv(txtDescripcion.getText());
            bitaB.setObservaciones(txtObservaciones.getText());            
            bitaB.setPorcentaje(cbPorcentaje.getSelectedIndex());
            Casos caso = new Casos();
            caso.UpdateCasoToFinalizar(bitaB);//ACTUALIZANDO caso a ...esperando respuesta
            bita.UpdateBitacora(bitaB);///Actualizando ultima bitacora
            JOptionPane.showMessageDialog(null, "Bitacora Finalizada!!");
            formWindowClosing(null);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnFinalizarMouseClicked

    private void btnUpdateBitacoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateBitacoraMouseClicked
        // PROGARMADOR: Actualiza Bitacora
        try {
            bitaB.setDescripActiv(txtDescripcion.getText());
            bitaB.setObservaciones(txtObservaciones.getText());            
            bitaB.setPorcentaje(cbPorcentaje.getSelectedIndex());
            Casos caso = new Casos();
            caso.UpdateCasoPorcent(bitaB);///Actualizando porcentaje
            bita.UpdateBitacora(bitaB);///Actualizando ultima bitacora
            JOptionPane.showMessageDialog(null, "Bitacora Actualizada!!");
            formWindowClosing(null);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUpdateBitacoraMouseClicked

    private void btnRechazarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRechazarMouseClicked
        // PROBADOR/TESTER update Caso a 6-Devuelto con observaciones
        try {
            if (txtObservaciones.getText().length() > 0) {
                caso.getDateLimit(casoB);
                if (h.Plus7Days(casoB)){ //Actualizar fecha limite                    
                    caso.UpdateDevolucion(casoB, txtObservaciones.getText());
                    JOptionPane.showMessageDialog(null, "Observaciones enviadas");
                    formWindowClosing(null);
                }                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRechazarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        // PROBADOR/TESTER update Caso a 7-Finalizado -->con la fecha de produccion        
        try {
            String fechaProd = txtFecha.getText();
            if (h.verificarFecha(fechaProd) && h.verificarAnio(fechaProd)) {
                if (!h.dateMaxNow(fechaProd) || !h.exitsFecha(fechaProd)) //Verificar si es menor a al fecha actual y si existe
                    JOptionPane.showMessageDialog(null, "La fecha ingresada no es valida");
                else {
                    //System.out.println("Bien");                    
                    casoB.setFecha_produccion(fechaProd);
                    casoB.setId_estado(7);//Caso Finalizado
                    caso.FinCaso(casoB);
                    JOptionPane.showMessageDialog(null, "Caso Finalizado");
                    formWindowClosing(null);
                }           
            }
            else 
                JOptionPane.showMessageDialog(null, "Verifique formato de la Fecha");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        if (h.CampoRestringuido(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtObservacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObservacionesKeyTyped
        if (h.CampoRestringuido(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtObservacionesKeyTyped

    private void txtFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMouseClicked
        if (txtFecha.getText().equals("02-02-2019")) {
            txtFecha.setText("");
        }
    }//GEN-LAST:event_txtFechaMouseClicked

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyReleased
        String fecha = txtFecha.getText();
        if (h.verificarFecha(fecha) && h.verificarAnio(fecha)) {
//            lblError.setText("");
//
//        } else {
//            lblError.setText("Verifique la fecha");
        }
    }//GEN-LAST:event_txtFechaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BitacoraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BitacoraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BitacoraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BitacoraC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BitacoraC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollListCasos;
    private javax.swing.JScrollPane ScrollListUser;
    private javax.swing.JPanel btnAceptar;
    private javax.swing.JPanel btnFinalizar;
    private javax.swing.JLabel btnMenuCasos;
    private javax.swing.JPanel btnRechazar;
    private javax.swing.JPanel btnUpdateBitacora;
    private javax.swing.JComboBox<String> cbPorcentaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCasoPro;
    private javax.swing.JLabel lblFechaProduccion;
    private javax.swing.JLabel lblIdCaso;
    private javax.swing.JLabel lblNombreCaso;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblProOoCasos;
    private javax.swing.JList<String> listCasos;
    private javax.swing.JList<String> listUser;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JTextArea txtDescripcion;
    public static javax.swing.JTextField txtFecha;
    private javax.swing.JTextArea txtObservaciones;
    public static javax.swing.JTextField txtProgramador;
    // End of variables declaration//GEN-END:variables

    private void VerlistaProCaso(int i){
        if (i == 0) {
            lblCasoPro.setVisible(true);
            ScrollListCasos.setVisible(true);            
        }
        else{
            lblCasoPro.setVisible(false);
            ScrollListCasos.setVisible(false);
        }
    }
    
    private void Ocultar() {
        ScrollListUser.setVisible(false);        
        this.setSize(490,this.getSize().height);
        pnlHead.setSize(490,pnlHead.getSize().height);
        pnlBody.setSize(490,pnlBody.getSize().height);
        btnMenuCasos.setLocation(pnlHead.getSize().width - btnMenuCasos.getSize().width-20, btnMenuCasos.getLocation().y);
    }

    private void Mostrar() {
        ScrollListUser.setVisible(true);
        this.setSize(656, this.getSize().height);
        pnlHead.setSize(656, pnlHead.getSize().height);
        pnlBody.setSize(656, pnlBody.getSize().height);
        btnMenuCasos.setLocation(pnlHead.getSize().width - btnMenuCasos.getSize().width-20, btnMenuCasos.getLocation().y);
    }

    private void ListarProgramadores(String Departamento) {
        try {                        
            empleado.getProTrabajando(String.valueOf(IdDepto), listUser);
        } catch (Exception e) {
            System.out.println(""+e);
        }
    }
     private void ListarCasos(String Departamento) {
         try {             
             listUser.clearSelection();             
             Casos caso = new Casos();
             caso.getIDCaso(Departamento.substring(0, 3),listUser);
             if (listUser.getModel().getSize()<1)
                 JOptionPane.showMessageDialog(null, "No han aperturado ningun caso");
             
         } catch (Exception e) {
         }
    }

    private void Inicio(int idCargo) {
        this.setLocationRelativeTo(null);
        this.setLayout(null);
        pnlHead.setLayout(null);
        pnlBody.setLayout(null);
        labelsDatosBita(0);
        VerlistaProCaso(1);
        Ocultar();        
        this.IdCargo = idCargo;
    }

    private void LlenarlistaProCaso() {
        listCasos.clearSelection();        
        DefaultListModel modelo = new DefaultListModel();
        for (BitacoraBean bitacoraBean : listBitaB) {
            modelo.addElement(bitacoraBean.getId_caso());
        }
        listCasos.setModel(modelo);
    }
    private void labelsDatosBita(int i) {
        if (i == 0) {
            lblIdCaso.setVisible(false);
            lblNombreCaso.setVisible(false);
            lblPorcentaje.setVisible(false);
        } else {
            lblIdCaso.setVisible(true);
            lblNombreCaso.setVisible(true);
            lblPorcentaje.setVisible(true);
        }
    }

    private void ShowBitacoraJD(String selectedValue) {
        for (BitacoraBean bitacoraBean : listBitaB) {
            if (bitacoraBean.getId_caso().equals(selectedValue)) {
                labelsDatosBita(1);
                lblIdCaso.setText(bitacoraBean.getId_caso());
                lblNombreCaso.setText(bitacoraBean.getNombre_caso());
                lblPorcentaje.setText(bitacoraBean.getPorcentaje()+" %");
                txtDescripcion.setText(bitacoraBean.getDescripActiv());
                txtObservaciones.setText(bitacoraBean.getObservaciones());
                break;
            }
        }
    }

    private void MostrarBitacoraJF() {
        labelsDatosBita(1);
        lblIdCaso.setText(bitaB.getId_caso());
        lblNombreCaso.setText(bitaB.getNombre_caso());
        lblPorcentaje.setText(bitaB.getPorcentaje() + " %");
        txtDescripcion.setText(bitaB.getDescripActiv());
        txtObservaciones.setText(bitaB.getObservaciones());        
    }

    private void llenandoCb() {
        lblPorcentaje.setVisible(false);
        cbPorcentaje.setLocation(lblPorcentaje.getLocation());
        for (int i = 0; i < 101; i++) 
            cbPorcentaje.addItem(i + "");
        cbPorcentaje.setSelectedIndex(bitaB.getPorcentaje());        
    }

    private void BtnsPro(int i) {
        if (i == 1) {
            btnFinalizar.setVisible(true);
            btnUpdateBitacora.setVisible(true);
        } else {
            btnFinalizar.setVisible(false);
            btnUpdateBitacora.setVisible(false);
        }
    }

    private void BtnsEmp(int i) {
        if (i == 1) {
            btnAceptar.setVisible(true);
            btnRechazar.setVisible(true);
            lblFechaProduccion.setVisible(true);
            txtFecha.setVisible(true);
        } else {
            btnAceptar.setVisible(false);
            btnRechazar.setVisible(false);
            lblFechaProduccion.setVisible(false);
            txtFecha.setVisible(false);
        }
    }

    private void noProniEmp() {
        BtnsPro(0);
        BtnsEmp(0);
        cbPorcentaje.setVisible(false);
        txtDescripcion.setEditable(false);
        txtObservaciones.setEditable(false);
    }

    private void ProgEmp(int i) {
        if (i == 0) {
            BtnsPro(1);
            BtnsEmp(0);
            txtDescripcion.setEditable(true);
            txtObservaciones.setEditable(false);
        }
        else {
            BtnsPro(0);
            BtnsEmp(1);
            txtDescripcion.setEditable(false);
            txtObservaciones.setEditable(true);
        }
    }

    private boolean isWaitAnswer() {
        try {
            caso = new Casos();
            casoB.setId_caso(bitaB.getId_caso());
            caso.getEstado(casoB);
            if (casoB.getId_estado() == 4) return true;
            else return false;
        } catch (Exception e) {
            return false;
        }
    }
    
}
