/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import Base.Empleado;
import Beans.EmpleadoBean;
import Help.Help;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jorge
 */
public class LoginW extends javax.swing.JFrame {
    private Color origin;
    private Help h  = new Help();
    private EmpleadoBean empB = new EmpleadoBean();
    private Empleado emp;
    private int j = 0;
    /**
     * Creates new form LoginW
     */
    public LoginW() {
        this.setUndecorated(true);
        initComponents();
        origin = pnlBackG.getBackground();
        lblErrorLogin.setVisible(false);
        this.setLocationRelativeTo(null);
        Fondo();
    }

    public void Fondo() {
        Imagen ima = new Imagen();
        pnlFondo.add(ima);        
        pnlFondo.repaint();        
    }
  
    public class Imagen extends javax.swing.JPanel {
        public Imagen() {
            this.setSize(pnlFondo.getSize()); 
        }
        public void paint(Graphics grafico) {
            Dimension dimen = this.getSize();
            ImageIcon Img = new ImageIcon(getClass().getResource("/tools/images/fondo1.png"));
            grafico.drawImage(Img.getImage(), 0, 0, dimen.width, dimen.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        pnlBackG1 = new javax.swing.JPanel();
        pnlFondo1 = new javax.swing.JPanel();
        jTxtCorreo1 = new javax.swing.JTextField();
        lblErrorLogin1 = new javax.swing.JLabel();
        txtContraseña1 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        pnlLogin3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnlBackG = new javax.swing.JPanel();
        pnlFondo = new javax.swing.JPanel();
        jTxtCorreo = new javax.swing.JTextField();
        lblErrorLogin = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        pnlLogin2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame1formWindowClosing(evt);
            }
        });

        pnlBackG1.setBackground(new java.awt.Color(59, 134, 139));

        jTxtCorreo1.setBackground(new java.awt.Color(36, 46, 68));
        jTxtCorreo1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jTxtCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        jTxtCorreo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCorreo1.setText("hola@empresa.sv");
        jTxtCorreo1.setBorder(null);
        jTxtCorreo1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTxtCorreo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtCorreo1MouseClicked(evt);
            }
        });
        jTxtCorreo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtCorreo1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCorreo1KeyTyped(evt);
            }
        });

        lblErrorLogin1.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        lblErrorLogin1.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorLogin1.setText("jLabel4");

        txtContraseña1.setBackground(new java.awt.Color(36, 46, 68));
        txtContraseña1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtContraseña1.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraseña1.setText("pass");
        txtContraseña1.setBorder(null);
        txtContraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseña1MouseClicked(evt);
            }
        });
        txtContraseña1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseña1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseña1KeyTyped(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/images/icons8-cerrar-ventana-50.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        pnlLogin3.setBackground(new java.awt.Color(89, 199, 198));
        pnlLogin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogin3MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Login");

        javax.swing.GroupLayout pnlLogin3Layout = new javax.swing.GroupLayout(pnlLogin3);
        pnlLogin3.setLayout(pnlLogin3Layout);
        pnlLogin3Layout.setHorizontalGroup(
            pnlLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogin3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(22, 22, 22))
        );
        pnlLogin3Layout.setVerticalGroup(
            pnlLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogin3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlFondo1Layout = new javax.swing.GroupLayout(pnlFondo1);
        pnlFondo1.setLayout(pnlFondo1Layout);
        pnlFondo1Layout.setHorizontalGroup(
            pnlFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo1Layout.createSequentialGroup()
                .addComponent(jTxtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFondo1Layout.createSequentialGroup()
                    .addGroup(pnlFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondo1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFondo1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(txtContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorLogin1)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(94, Short.MAX_VALUE))
                .addGroup(pnlFondo1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)
                    .addComponent(pnlLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlFondo1Layout.setVerticalGroup(
            pnlFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondo1Layout.createSequentialGroup()
                .addGroup(pnlFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondo1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jTxtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblErrorLogin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBackG1Layout = new javax.swing.GroupLayout(pnlBackG1);
        pnlBackG1.setLayout(pnlBackG1Layout);
        pnlBackG1Layout.setHorizontalGroup(
            pnlBackG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackG1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBackG1Layout.setVerticalGroup(
            pnlBackG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackG1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlBackG.setBackground(new java.awt.Color(59, 134, 139));

        jTxtCorreo.setBackground(new java.awt.Color(36, 46, 68));
        jTxtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jTxtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jTxtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCorreo.setText("hola@empresa.sv");
        jTxtCorreo.setBorder(null);
        jTxtCorreo.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTxtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtCorreoMouseClicked(evt);
            }
        });
        jTxtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtCorreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCorreoKeyTyped(evt);
            }
        });

        lblErrorLogin.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        lblErrorLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorLogin.setText("jLabel4");

        txtContraseña.setBackground(new java.awt.Color(36, 46, 68));
        txtContraseña.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraseña.setText("pass");
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyTyped(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/images/icons8-cerrar-ventana-50.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        pnlLogin2.setBackground(new java.awt.Color(89, 199, 198));
        pnlLogin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogin2MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Login");

        javax.swing.GroupLayout pnlLogin2Layout = new javax.swing.GroupLayout(pnlLogin2);
        pnlLogin2.setLayout(pnlLogin2Layout);
        pnlLogin2Layout.setHorizontalGroup(
            pnlLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogin2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(22, 22, 22))
        );
        pnlLogin2Layout.setVerticalGroup(
            pnlLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogin2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFondoLayout.createSequentialGroup()
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorLogin)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(94, Short.MAX_VALUE))
                .addGroup(pnlFondoLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)
                    .addComponent(pnlLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblErrorLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBackGLayout = new javax.swing.GroupLayout(pnlBackG);
        pnlBackG.setLayout(pnlBackGLayout);
        pnlBackGLayout.setHorizontalGroup(
            pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBackGLayout.setVerticalGroup(
            pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCorreoMouseClicked
        if (jTxtCorreo.getText().equals("hola@empresa.sv"))
        jTxtCorreo.setText("");
    }//GEN-LAST:event_jTxtCorreoMouseClicked

    private void jTxtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCorreoKeyReleased
        if (h.validarCorreo(jTxtCorreo.getText()) )
        pnlBackG.setBackground(origin);
        else pnlBackG.setBackground(Color.red);
    }//GEN-LAST:event_jTxtCorreoKeyReleased

    private void jTxtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCorreoKeyTyped
        if ((evt.getKeyChar() == KeyEvent.VK_SPACE) || h.CampoRestringuido(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtCorreoKeyTyped

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        if (j == 0){
            txtContraseña.setText("");
            j++;
        }
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void txtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_SPACE || h.CampoRestringuido(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtContraseñaKeyTyped

    private void txtContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            pnlLogin2MouseClicked(null);
        }
    }//GEN-LAST:event_txtContraseñaKeyPressed

    private void pnlLogin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogin2MouseClicked
        pnlLogin2.setBackground(new Color (3,147,90));
        try {
            emp = new Empleado();
            String pass = new String(txtContraseña.getPassword());
            if (!pass.equals("") && !jTxtCorreo.getText().equals("")) {
                if (emp.existUSer(jTxtCorreo.getText(), pass, empB)) {
                    emp.getLogin(empB);
                    new Menu(empB).setVisible(true);
                    this.dispose();
                } else {
                    lblErrorLogin.setText("Usuario/contraseña incorrectos");
                    lblErrorLogin.setVisible(true);
                }
            }
            else{
                lblErrorLogin.setText("Campos vacíos");
                lblErrorLogin.setVisible(true);
            }
        } catch (SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Error inicio de sesión");
        }
    }//GEN-LAST:event_pnlLogin2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        formWindowClosing(null);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int j = JOptionPane.showConfirmDialog(this,"¿ Estas seguro de salir?");
        if (j == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jTxtCorreo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCorreo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCorreo1MouseClicked

    private void jTxtCorreo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCorreo1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCorreo1KeyReleased

    private void jTxtCorreo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCorreo1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCorreo1KeyTyped

    private void txtContraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseña1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseña1MouseClicked

    private void txtContraseña1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseña1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseña1KeyPressed

    private void txtContraseña1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseña1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseña1KeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void pnlLogin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogin3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlLogin3MouseClicked

    private void jFrame1formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrame1formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTxtCorreo;
    private javax.swing.JTextField jTxtCorreo1;
    private javax.swing.JLabel lblErrorLogin;
    private javax.swing.JLabel lblErrorLogin1;
    private javax.swing.JPanel pnlBackG;
    private javax.swing.JPanel pnlBackG1;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFondo1;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLogin1;
    private javax.swing.JPanel pnlLogin2;
    private javax.swing.JPanel pnlLogin3;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JPasswordField txtContraseña1;
    // End of variables declaration//GEN-END:variables
}
