/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import Base.Casos;
import Beans.CasoBean;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListModel;

/**
 *
 * @author less_
 */
public class Menu extends javax.swing.JFrame {
    private String caden;
    private String[] rowfields;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    public Menu(String cadena) {
        initComponents();
        this.setLocationRelativeTo(null);
        caden = cadena;
        rowfields = cadena.split("-");
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblConfigPerfil = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlBarra = new javax.swing.JPanel();
        pnlJD = new javax.swing.JPanel();
        btnSolicitudesJD = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBitacorasJD = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnListaProgramadores = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        btnManteniEmpleados = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlJF = new javax.swing.JPanel();
        btnSolicitarCasoJF = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnBitacorasJF = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnListaEmpleados = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnlCasos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUtilidad = new javax.swing.JList<>();
        btnOkCasoJD = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnNoCasoJD = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnVer = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 51));
        setForeground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(89, 199, 198));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombre.setText("Nombre");

        lblCargo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCargo.setText("Cargo");

        lblDepartamento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDepartamento.setText("Departamento");

        lblID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblID.setText("ID");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/images/icons8-gerente-64 (1).png"))); // NOI18N

        lblConfigPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tools/images/icons8-servicios-filled-50.png"))); // NOI18N
        lblConfigPerfil.setToolTipText("Configurar mi perfil");
        lblConfigPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfigPerfilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblID)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblDepartamento)
                    .addComponent(lblCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(lblConfigPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDepartamento)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblID)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblConfigPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 90));

        pnlMenu.setBackground(new java.awt.Color(36, 46, 68));

        pnlBarra.setBackground(new java.awt.Color(34, 46, 88));

        pnlJD.setBackground(new java.awt.Color(34, 46, 88));

        btnSolicitudesJD.setBackground(new java.awt.Color(89, 199, 198));
        btnSolicitudesJD.setToolTipText("Solicitudes de casos");
        btnSolicitudesJD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitudesJDMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Solicitudes");

        javax.swing.GroupLayout btnSolicitudesJDLayout = new javax.swing.GroupLayout(btnSolicitudesJD);
        btnSolicitudesJD.setLayout(btnSolicitudesJDLayout);
        btnSolicitudesJDLayout.setHorizontalGroup(
            btnSolicitudesJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSolicitudesJDLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );
        btnSolicitudesJDLayout.setVerticalGroup(
            btnSolicitudesJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSolicitudesJDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnBitacorasJD.setBackground(new java.awt.Color(89, 199, 198));
        btnBitacorasJD.setToolTipText("Bitacora de Programadores");
        btnBitacorasJD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBitacorasJDMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bitacoras");

        javax.swing.GroupLayout btnBitacorasJDLayout = new javax.swing.GroupLayout(btnBitacorasJD);
        btnBitacorasJD.setLayout(btnBitacorasJDLayout);
        btnBitacorasJDLayout.setHorizontalGroup(
            btnBitacorasJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBitacorasJDLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        btnBitacorasJDLayout.setVerticalGroup(
            btnBitacorasJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBitacorasJDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnListaProgramadores.setBackground(new java.awt.Color(89, 199, 198));
        btnListaProgramadores.setToolTipText("Listado de programadores");
        btnListaProgramadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaProgramadoresMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Programadores");

        javax.swing.GroupLayout btnListaProgramadoresLayout = new javax.swing.GroupLayout(btnListaProgramadores);
        btnListaProgramadores.setLayout(btnListaProgramadoresLayout);
        btnListaProgramadoresLayout.setHorizontalGroup(
            btnListaProgramadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaProgramadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnListaProgramadoresLayout.setVerticalGroup(
            btnListaProgramadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaProgramadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlJDLayout = new javax.swing.GroupLayout(pnlJD);
        pnlJD.setLayout(pnlJDLayout);
        pnlJDLayout.setHorizontalGroup(
            pnlJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSolicitudesJD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBitacorasJD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListaProgramadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pnlJDLayout.setVerticalGroup(
            pnlJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSolicitudesJD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnBitacorasJD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnListaProgramadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAdmin.setBackground(new java.awt.Color(34, 46, 88));

        btnManteniEmpleados.setBackground(new java.awt.Color(89, 199, 198));
        btnManteniEmpleados.setToolTipText("Mantenimiento de Empleados");
        btnManteniEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManteniEmpleadosMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mantenimiento de Empleados");

        javax.swing.GroupLayout btnManteniEmpleadosLayout = new javax.swing.GroupLayout(btnManteniEmpleados);
        btnManteniEmpleados.setLayout(btnManteniEmpleadosLayout);
        btnManteniEmpleadosLayout.setHorizontalGroup(
            btnManteniEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManteniEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnManteniEmpleadosLayout.setVerticalGroup(
            btnManteniEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManteniEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(btnManteniEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnManteniEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlJF.setBackground(new java.awt.Color(34, 46, 88));

        btnSolicitarCasoJF.setBackground(new java.awt.Color(89, 199, 198));
        btnSolicitarCasoJF.setToolTipText("Mandar una solicitud de caso");
        btnSolicitarCasoJF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitarCasoJFMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Solicitar Caso");

        javax.swing.GroupLayout btnSolicitarCasoJFLayout = new javax.swing.GroupLayout(btnSolicitarCasoJF);
        btnSolicitarCasoJF.setLayout(btnSolicitarCasoJFLayout);
        btnSolicitarCasoJFLayout.setHorizontalGroup(
            btnSolicitarCasoJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSolicitarCasoJFLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnSolicitarCasoJFLayout.setVerticalGroup(
            btnSolicitarCasoJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSolicitarCasoJFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnBitacorasJF.setBackground(new java.awt.Color(89, 199, 198));
        btnBitacorasJF.setToolTipText("Ver bitacoras de casos aperturados");
        btnBitacorasJF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBitacorasJFMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bitacoras");

        javax.swing.GroupLayout btnBitacorasJFLayout = new javax.swing.GroupLayout(btnBitacorasJF);
        btnBitacorasJF.setLayout(btnBitacorasJFLayout);
        btnBitacorasJFLayout.setHorizontalGroup(
            btnBitacorasJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBitacorasJFLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        btnBitacorasJFLayout.setVerticalGroup(
            btnBitacorasJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBitacorasJFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnListaEmpleados.setBackground(new java.awt.Color(89, 199, 198));
        btnListaEmpleados.setToolTipText("Listado de Empleados");
        btnListaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaEmpleadosMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Empleados");

        javax.swing.GroupLayout btnListaEmpleadosLayout = new javax.swing.GroupLayout(btnListaEmpleados);
        btnListaEmpleados.setLayout(btnListaEmpleadosLayout);
        btnListaEmpleadosLayout.setHorizontalGroup(
            btnListaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaEmpleadosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        btnListaEmpleadosLayout.setVerticalGroup(
            btnListaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlJFLayout = new javax.swing.GroupLayout(pnlJF);
        pnlJF.setLayout(pnlJFLayout);
        pnlJFLayout.setHorizontalGroup(
            pnlJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJFLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnSolicitarCasoJF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBitacorasJF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnListaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlJFLayout.setVerticalGroup(
            pnlJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSolicitarCasoJF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnBitacorasJF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnListaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout pnlBarraLayout = new javax.swing.GroupLayout(pnlBarra);
        pnlBarra.setLayout(pnlBarraLayout);
        pnlBarraLayout.setHorizontalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnlJF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlJD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlBarraLayout.setVerticalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlJD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlJF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pnlCasos.setBackground(new java.awt.Color(36, 46, 68));

        listUtilidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listUtilidad.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listUtilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUtilidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listUtilidad);

        btnOkCasoJD.setBackground(new java.awt.Color(89, 199, 198));
        btnOkCasoJD.setToolTipText("Aceptar caso");
        btnOkCasoJD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkCasoJDMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Aceptar Caso");

        javax.swing.GroupLayout btnOkCasoJDLayout = new javax.swing.GroupLayout(btnOkCasoJD);
        btnOkCasoJD.setLayout(btnOkCasoJDLayout);
        btnOkCasoJDLayout.setHorizontalGroup(
            btnOkCasoJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnOkCasoJDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnOkCasoJDLayout.setVerticalGroup(
            btnOkCasoJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnOkCasoJDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnNoCasoJD.setBackground(new java.awt.Color(89, 199, 198));
        btnNoCasoJD.setToolTipText("Rechazar Caso");
        btnNoCasoJD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNoCasoJDMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Rechazar Caso");
        jLabel15.setToolTipText("");

        javax.swing.GroupLayout btnNoCasoJDLayout = new javax.swing.GroupLayout(btnNoCasoJD);
        btnNoCasoJD.setLayout(btnNoCasoJDLayout);
        btnNoCasoJDLayout.setHorizontalGroup(
            btnNoCasoJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNoCasoJDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnNoCasoJDLayout.setVerticalGroup(
            btnNoCasoJDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNoCasoJDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnVer.setBackground(new java.awt.Color(89, 199, 198));
        btnVer.setToolTipText("Ver Bitacora");
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ver Caso");

        javax.swing.GroupLayout btnVerLayout = new javax.swing.GroupLayout(btnVer);
        btnVer.setLayout(btnVerLayout);
        btnVerLayout.setHorizontalGroup(
            btnVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(28, 28, 28))
        );
        btnVerLayout.setVerticalGroup(
            btnVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCasosLayout = new javax.swing.GroupLayout(pnlCasos);
        pnlCasos.setLayout(pnlCasosLayout);
        pnlCasosLayout.setHorizontalGroup(
            pnlCasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCasosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlCasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNoCasoJD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOkCasoJD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        pnlCasosLayout.setVerticalGroup(
            pnlCasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnlCasosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnOkCasoJD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnNoCasoJD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(pnlCasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(pnlBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(106, Short.MAX_VALUE))))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(pnlBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(pnlCasos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 580, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void lblConfigPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfigPerfilMouseClicked
        Perfil perfil = new Perfil(caden);
        perfil.setVisible(true);
    }//GEN-LAST:event_lblConfigPerfilMouseClicked

    private void btnManteniEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManteniEmpleadosMouseClicked
        MantenimientoEmpleados call = new MantenimientoEmpleados();
        call.setVisible(true);
    }//GEN-LAST:event_btnManteniEmpleadosMouseClicked

    private void btnSolicitudesJDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudesJDMouseClicked
        try {
            String DeptoCaso = lblDepartamento.getText().charAt(0) + "" + lblDepartamento.getText().charAt(1) + "" + lblDepartamento.getText().charAt(2);
            Casos casoSoli = new Casos();            
            casoSoli.getSolicitudesJD(DeptoCaso, listUtilidad);
            if (listUtilidad.getModel().getSize() == 0)
                JOptionPane.showMessageDialog(null, "No hay solicitudes");
            else {
                pnlCasos.setVisible(true);                
                btnNoCasoJD.setLocation(btnVer.getLocation());
                btnVer.setVisible(false);
            }
        } catch (Exception e) {            
        }
    }//GEN-LAST:event_btnSolicitudesJDMouseClicked

    private void btnBitacorasJDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitacorasJDMouseClicked
        try {
            Bitacora n = new Bitacora(lblDepartamento.getText());
        n.setVisible(true);
        } catch (Exception e) {
        }
        //para bitacoras con Programadores
    }//GEN-LAST:event_btnBitacorasJDMouseClicked

    private void btnListaProgramadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaProgramadoresMouseClicked
        //lista con los nombres de los programadores
    }//GEN-LAST:event_btnListaProgramadoresMouseClicked

    private void btnSolicitarCasoJFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarCasoJFMouseClicked

        try {//Enviando Nombre del departamento
            if (Solicitud.ban == 0) {
                Solicitud soli = new Solicitud(rowfields[5]);
                soli.setVisible(true);
            }
            else 
                JOptionPane.showMessageDialog(null, "aqui");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSolicitarCasoJFMouseClicked

    private void btnBitacorasJFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitacorasJFMouseClicked
        
        //bitacoras por departamento
    }//GEN-LAST:event_btnBitacorasJFMouseClicked

    private void btnListaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaEmpleadosMouseClicked
        //Lista con empleados por departamento
    }//GEN-LAST:event_btnListaEmpleadosMouseClicked

    private void btnOkCasoJDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkCasoJDMouseClicked
        try {
            if (DescripcionCaso.ban == 0) {
                DescripcionCaso descrip = new DescripcionCaso(0, listUtilidad.getSelectedValue().toString());
                descrip.setVisible(true);                
            }
            cerrarCasoJD();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnOkCasoJDMouseClicked

    private void btnNoCasoJDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoCasoJDMouseClicked
        try {
            if (DescripcionCaso.ban == 0) {
                DescripcionCaso descrip = new DescripcionCaso(1, listUtilidad.getSelectedValue().toString());
                descrip.setVisible(true);                
            }
            cerrarCasoJD();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnNoCasoJDMouseClicked

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerMouseClicked

    private void listUtilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUtilidadMouseClicked
        //JOptionPane.showMessageDialog(null, ""+listUtilidad.getSelectedValue().toString());
        btnOkCasoJD.setVisible(true);
        btnNoCasoJD.setVisible(true);
    }//GEN-LAST:event_listUtilidadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBitacorasJD;
    private javax.swing.JPanel btnBitacorasJF;
    private javax.swing.JPanel btnListaEmpleados;
    private javax.swing.JPanel btnListaProgramadores;
    private javax.swing.JPanel btnManteniEmpleados;
    private javax.swing.JPanel btnNoCasoJD;
    private javax.swing.JPanel btnOkCasoJD;
    private javax.swing.JPanel btnSolicitarCasoJF;
    private javax.swing.JPanel btnSolicitudesJD;
    private javax.swing.JPanel btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblConfigPerfil;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JList<String> listUtilidad;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlBarra;
    private javax.swing.JPanel pnlCasos;
    private javax.swing.JPanel pnlJD;
    private javax.swing.JPanel pnlJF;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables

    private void inicio() {
        pnlMenu.setLayout(null);
        pnlBarra.setLayout(null);
        pnlCasos.setLayout(null);
        cerrarCasoJD();
        switch (llenarDatos()) {
            case "0":
                darMenu(pnlAdmin);
                break;
            case "1":
                darMenu(pnlJD);
                break;
            case "2":
                darMenu(pnlJF);
                break;
            case "3":
                break;
            case "4":
                break;
        }        
    }

    private String llenarDatos() {        
        if(rowfields[2].equals("0")) lblDepartamento.setText("");
        else lblDepartamento.setText(rowfields[5]);
        lblID.setText("ID " + rowfields[0]);
        lblNombre.setText(rowfields[1]);
        lblCargo.setText(rowfields[3]);
        return rowfields[2];
    }

    private void darMenu(JPanel pnlMostrar) {
        for (Component obj : pnlBarra.getComponents()) {
            if(obj != pnlMostrar) {
                obj.setVisible(false);
                pnlMostrar.setLocation(pnlAdmin.getLocation());
                pnlBarra.setSize(pnlBarra.getSize().width,pnlMostrar.getSize().height+15);
            }
        }
        pnlCasos.setLocation(20, pnlBarra.getSize().height + 10);
    }

    private void cerrarCasoJD() {
        pnlCasos.setVisible(false);
        btnOkCasoJD.setVisible(false);
        btnNoCasoJD.setVisible(false);
    }
}
